name: Regenerate the plugin docs code
on:
  schedule:
    # run a bit before midnight when go deps change
    - cron: '0 23 * * *'

  # allow manual triggering
  workflow_dispatch: {}
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://golang:1.23
        name: Regenerate the plugins docs
        id: regenerate
        env:
          GIT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        with:
          entrypoint: ./regen-plugins.sh
      - name: Create pr for regenerated plugin docs
        if: ${{ steps.regenerate.outputs.changed == 'true' }}
        uses: ./.github/actions/create-pr-for-plugin-docs
        with:
          token: ${{ secrets.GIT_BOT_TOKEN }}
          run_id: ${{ github.run_id }}
